version: "3.8"
services:
  dev: &app
    build:
      context: Docker/php
      dockerfile: Dockerfile
    environment:
      APP_ENV: development
    volumes:
      - ".:/app"
  test:
    <<: *app
    environment:
      APP_ENV: test
  # dynamodb-admin:
  #   image: aaronshaf/dynamodb-admin
