version: "3.8"
services:
  dev: &app
    build:
      context: Docker/php
      dockerfile: Dockerfile
    environment:
      APP_ENV: development
    volumes:
      - ".:/app"
    command: "sleep infinity"
    depends_on:
      - dynamodb
  test:
    <<: *app
    environment:
      APP_ENV: test
  dynamodb:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -dbPath ."
    volumes:
      - "dynamodb:/home/dynamodblocal"
    ports:
      - "18000:8000"
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb
volumes:
  dynamodb:
    driver: local
