name: ci
on: [push]
jobs:
  # phpcs
  # phpstan
  # phpunit
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - run: php --version
      - uses: actions/cache@v3
        env:
          cache-name: cache-composer
        with:
          path: vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - uses: baschny/php-composer-action@v1
      - run: vendor/bin/phpcs
      - run: vendor/bin/phpstan
  test:
    needs: static-analysis
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        # php-versions: ["7.4", "8.0", "8.1"]
        # exclude:
        #   - operating-system: windows-latest
        #     php-versions: "7.4"
    steps:
      - uses: actions/checkout@v3
      # - uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: ${{ matrix.php-versions }}
      #     coverage: pcov
      - run: php --version
      - uses: actions/cache@v3
        env:
          cache-name: cache-composer
        with:
          path: vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - uses: baschny/php-composer-action@v1
      - run: vendor/bin/phpunit
