name: PHPUnit

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
    paths:
      - "**"
      - "!*.md"
  # pull_request:
  #   paths:
  #     - "**"
  #     - "!*.md"

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ["7.4", "8.0", "8.1"]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: pcov
      - run: php --version
      - run: composer --version
      - uses: actions/cache@v3
        env:
          cache-name: cache-composer
        with:
          path: vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - uses: baschny/php-composer-action@v1
      - run: composer phpunit
